const cidadesSp = [
  "Sao Paulo",
  "Adamantina",
  "Adolfo",
  "Aguai",
  "Aguas da Prata",
  "Aguas de Lindoia",
  "Aguas de Santa Barbara",
  "Aguas de Sao Pedro",
  "Agudos",
  "Alambari",
  "Alfredo Marcondes",
  "Altair",
  "Altinopolis",
  "Alto Alegre",
  "Aluminio",
  "Alvares Florence",
  "Alvares Machado",
  "Alvaro de Carvalho",
  "Alvinlandia",
  "Americana",
  "Americo Brasiliense",
  "Americo de Campos",
  "Amparo",
  "Analandia",
  "Andradina",
  "Angatuba",
  "Anhembi",
  "Anhumas",
  "Aparecida d'Oeste",
  "Aparecida",
  "Apiai",
  "Aracariguama",
  "Aracatuba",
  "Aracoiaba da Serra",
  "Aramina",
  "Arandu",
  "Arapei",
  "Araraquara",
  "Araras",
  "Arco-Iris",
  "Arealva",
  "Areias",
  "Areiopolis",
  "Ariranha",
  "Artur Nogueira",
  "Aruja",
  "Aspasia",
  "Assis",
  "Atibaia",
  "Auriflama",
  "Avai",
  "Avanhandava",
  "Avare",
  "Bady Bassitt",
  "Balbinos",
  "Balsamo",
  "Bananal",
  "Barao de Antonina",
  "Barbosa",
  "Bariri",
  "Barra Bonita",
  "Barra do Chapeu",
  "Barra do Turvo",
  "Barretos",
  "Barrinha",
  "Barueri",
  "Bastos",
  "Batatais",
  "Bauru",
  "Bebedouro",
  "Bento de Abreu",
  "Bernardino de Campos",
  "Bertioga",
  "Bilac",
  "Birigui",
  "Biritiba-Mirim",
  "Boa Esperanca do Sul",
  "Bocaina",
  "Bofete",
  "Boituva",
  "Bom Jesus dos Perdoes",
  "Bom Sucesso de Itarare",
  "Bora",
  "Boraceia",
  "Borborema",
  "Borebi",
  "Botucatu",
  "Braganca Paulista",
  "Brauna",
  "Brejo Alegre",
  "Brodosqui",
  "Brotas",
  "Buri",
  "Buritama",
  "Buritizal",
  "Cabralia Paulista",
  "Cabreuva",
  "Cacapava",
  "Cachoeira Paulista",
  "Caconde",
  "Cafelandia",
  "Caiabu",
  "Caieiras",
  "Caiua",
  "Cajamar",
  "Cajati",
  "Cajobi",
  "Cajuru",
  "Campina do Monte Alegre",
  "Campinas",
  "Campo Limpo Paulista",
  "Campos Novos Paulista",
  "Campos do Jordao",
  "Cananeia",
  "Canas",
  "Candido Mota",
  "Candido Rodrigues",
  "Canitar",
  "Capao Bonito",
  "Capela do Alto",
  "Capivari",
  "Caraguatatuba",
  "Carapicuiba",
  "Cardoso",
  "Casa Branca",
  "Cassia dos Coqueiros",
  "Castilho",
  "Catanduva",
  "Catigua",
  "Cedral",
  "Cerqueira Cesar",
  "Cerquilho",
  "Cesario Lange",
  "Charqueada",
  "Chavantes",
  "Clementina",
  "Colina",
  "Colombia",
  "Conchal",
  "Conchas",
  "Cordeiropolis",
  "Coroados",
  "Coronel Macedo",
  "Corumbatai",
  "Cosmopolis",
  "Cosmorama",
  "Cotia",
  "Cravinhos",
  "Cristais Paulista",
  "Cruzalia",
  "Cruzeiro",
  "Cubatao",
  "Cunha",
  "Descalvado",
  "Diadema",
  "Dirce Reis",
  "Divinolandia",
  "Dobrada",
  "Dois Corregos",
  "Dolcinopolis",
  "Dourado",
  "Dracena",
  "Duartina",
  "Dumont",
  "Echapora",
  "Eldorado",
  "Elias Fausto",
  "Elisiario",
  "Embauba",
  "Embu",
  "Embu-Guacu",
  "Emilianopolis",
  "Engenheiro Coelho",
  "Espirito Santo do Pinhal",
  "Espirito Santo do Turvo",
  "Estiva Gerbi",
  "Estrela d'Oeste",
  "Estrela do Norte",
  "Euclides da Cunha Paulista",
  "Fartura",
  "Fernando Prestes",
  "Fernandopolis",
  "Fernao",
  "Ferraz de Vasconcelos",
  "Flora Rica",
  "Floreal",
  "Florida Paulista",
  "Florinia",
  "Franca",
  "Francisco Morato",
  "Franco da Rocha",
  "Gabriel Monteiro",
  "Galia",
  "Garca",
  "Gastao Vidigal",
  "Gaviao Peixoto",
  "General Salgado",
  "Getulina",
  "Glicerio",
  "Guaicara",
  "Guaimbe",
  "Guaira",
  "Guapiacu",
  "Guapiara",
  "Guara",
  "Guaracai",
  "Guaraci",
  "Guarani d'Oeste",
  "Guaranta",
  "Guararapes",
  "Guararema",
  "Guaratingueta",
  "Guarei",
  "Guariba",
  "Guaruja",
  "Guarulhos",
  "Guatapara",
  "Guzolandia",
  "Herculandia",
  "Holambra",
  "Hortolandia",
  "Iacanga",
  "Iacri",
  "Iaras",
  "Ibate",
  "Ibira",
  "Ibirarema",
  "Ibitinga",
  "Ibiuna",
  "Icem",
  "Iepe",
  "Igaracu do Tiete",
  "Igarapava",
  "Igarata",
  "Iguape",
  "Ilha Comprida",
  "Ilha Solteira",
  "Ilhabela",
  "Indaiatuba",
  "Indiana",
  "Indiapora",
  "Inubia Paulista",
  "Ipaucu",
  "Ipero",
  "Ipeuna",
  "Ipigua",
  "Iporanga",
  "Ipua",
  "Iracemapolis",
  "Irapua",
  "Irapuru",
  "Itabera",
  "Itai",
  "Itajobi",
  "Itaju",
  "Itanhaem",
  "Itaoca",
  "Itapecerica da Serra",
  "Itapetininga",
  "Itapeva",
  "Itapevi",
  "Itapira",
  "Itapirapua Paulista",
  "Itapolis",
  "Itaporanga",
  "Itapui",
  "Itapura",
  "Itaquaquecetuba",
  "Itarare",
  "Itariri",
  "Itatiba",
  "Itatinga",
  "Itirapina",
  "Itirapua",
  "Itobi",
  "Itu",
  "Itupeva",
  "Ituverava",
  "Jaborandi",
  "Jaboticabal",
  "Jacarei",
  "Jaci",
  "Jacupiranga",
  "Jaguariuna",
  "Jales",
  "Jambeiro",
  "Jandira",
  "Jardinopolis",
  "Jarinu",
  "Jau",
  "Jeriquara",
  "Joanopolis",
  "Joao Ramalho",
  "Jose Bonifacio",
  "Julio Mesquita",
  "Jumirim",
  "Jundiai",
  "Junqueiropolis",
  "Juquia",
  "Juquitiba",
  "Lagoinha",
  "Laranjal Paulista",
  "Lavinia",
  "Lavrinhas",
  "Leme",
  "Lencois Paulista",
  "Limeira",
  "Lindoia",
  "Lins",
  "Lorena",
  "Lourdes",
  "Louveira",
  "Lucelia",
  "Lucianopolis",
  "Luis Antonio",
  "Luiziania",
  "Lupercio",
  "Lutecia",
  "Macatuba",
  "Macaubal",
  "Macedonia",
  "Magda",
  "Mairinque",
  "Mairipora",
  "Manduri",
  "Maraba Paulista",
  "Maracai",
  "Marapoama",
  "Mariapolis",
  "Marilia",
  "Marinopolis",
  "Martinopolis",
  "Matao",
  "Maua",
  "Mendonca",
  "Meridiano",
  "Mesopolis",
  "Miguelopolis",
  "Mineiros do Tiete",
  "Mira Estrela",
  "Miracatu",
  "Mirandopolis",
  "Mirante do Paranapanema",
  "Mirassol",
  "Mirassolandia",
  "Mococa",
  "Mogi Guacu",
  "Moji das Cruzes",
  "Moji-Mirim",
  "Mombuca",
  "Moncoes",
  "Mongagua",
  "Monte Alegre do Sul",
  "Monte Alto",
  "Monte Aprazivel",
  "Monte Azul Paulista",
  "Monte Castelo",
  "Monte Mor",
  "Monteiro Lobato",
  "Morro Agudo",
  "Morungaba",
  "Motuca",
  "Murutinga do Sul",
  "Nantes",
  "Narandiba",
  "Natividade da Serra",
  "Nazare Paulista",
  "Neves Paulista",
  "Nhandeara",
  "Nipoa",
  "Nova Alianca",
  "Nova Campina",
  "Nova Canaa Paulista",
  "Nova Castilho",
  "Nova Europa",
  "Nova Granada",
  "Nova Guataporanga",
  "Nova Independencia",
  "Nova Luzitania",
  "Nova Odessa",
  "Novais",
  "Novo Horizonte",
  "Nuporanga",
  "Ocaucu",
  "Oleo",
  "Olimpia",
  "Onda Verde",
  "Oriente",
  "Orindiuva",
  "Orlandia",
  "Osasco",
  "Oscar Bressane",
  "Osvaldo Cruz",
  "Ourinhos",
  "Ouro Verde",
  "Ouroeste",
  "Pacaembu",
  "Palestina",
  "Palmares Paulista",
  "Palmeira d'Oeste",
  "Palmital",
  "Panorama",
  "Paraguacu Paulista",
  "Paraibuna",
  "Paraiso",
  "Paranapanema",
  "Paranapua",
  "Parapua",
  "Pardinho",
  "Pariquera-Acu",
  "Parisi",
  "Patrocinio Paulista",
  "Pauliceia",
  "Paulinia",
  "Paulistania",
  "Paulo de Faria",
  "Pederneiras",
  "Pedra Bela",
  "Pedranopolis",
  "Pedregulho",
  "Pedreira",
  "Pedrinhas Paulista",
  "Pedro de Toledo",
  "Penapolis",
  "Pereira Barreto",
  "Pereiras",
  "Peruibe",
  "Piacatu",
  "Piedade",
  "Pilar do Sul",
  "Pindamonhangaba",
  "Pindorama",
  "Pinhalzinho",
  "Piquerobi",
  "Piquete",
  "Piracaia",
  "Piracicaba",
  "Piraju",
  "Pirajui",
  "Pirangi",
  "Pirapora do Bom Jesus",
  "Pirapozinho",
  "Pirassununga",
  "Piratininga",
  "Pitangueiras",
  "Planalto",
  "Platina",
  "Poa",
  "Poloni",
  "Pompeia",
  "Pongai",
  "Pontal",
  "Pontalinda",
  "Pontes Gestal",
  "Populina",
  "Porangaba",
  "Porto Feliz",
  "Porto Ferreira",
  "Potim",
  "Potirendaba",
  "Pracinha",
  "Pradopolis",
  "Praia Grande",
  "Pratania",
  "Presidente Alves",
  "Presidente Bernardes",
  "Presidente Epitacio",
  "Presidente Prudente",
  "Presidente Venceslau",
  "Promissao",
  "Quadra",
  "Quata",
  "Queiroz",
  "Queluz",
  "Quintana",
  "Rafard",
  "Rancharia",
  "Redencao da Serra",
  "Regente Feijo",
  "Reginopolis",
  "Registro",
  "Restinga",
  "Ribeira",
  "Ribeirao Bonito",
  "Ribeirao Branco",
  "Ribeirao Corrente",
  "Ribeirao Grande",
  "Ribeirao Pires",
  "Ribeirao Preto",
  "Ribeirao do Sul",
  "Ribeirao dos Indios",
  "Rifaina",
  "Rincao",
  "Rinopolis",
  "Rio Claro",
  "Rio Grande da Serra",
  "Rio das Pedras",
  "Riolandia",
  "Riversul",
  "Rosana",
  "Roseira",
  "Rubiacea",
  "Rubineia",
  "Sabino",
  "Sagres",
  "Sales Oliveira",
  "Sales",
  "Salesopolis",
  "Salmourao",
  "Saltinho",
  "Salto Grande",
  "Salto de Pirapora",
  "Salto",
  "Sandovalina",
  "Santa Adelia",
  "Santa Albertina",
  "Santa Barbara d'Oeste",
  "Santa Branca",
  "Santa Clara d'Oeste",
  "Santa Cruz da Conceicao",
  "Santa Cruz da Esperanca",
  "Santa Cruz das Palmeiras",
  "Santa Cruz do Rio Pardo",
  "Santa Ernestina",
  "Santa Fe do Sul",
  "Santa Gertrudes",
  "Santa Isabel",
  "Santa Lucia",
  "Santa Maria da Serra",
  "Santa Mercedes",
  "Santa Rita d'Oeste",
  "Santa Rita do Passa Quatro",
  "Santa Rosa de Viterbo",
  "Santa Salete",
  "Santana da Ponte Pensa",
  "Santana de Parnaiba",
  "Santo Anastacio",
  "Santo Andre",
  "Santo Antonio da Alegria",
  "Santo Antonio de Posse",
  "Santo Antonio do Aracangua",
  "Santo Antonio do Jardim",
  "Santo Antonio do Pinhal",
  "Santo Expedito",
  "Santopolis do Aguapei",
  "Santos",
  "Sao Bento do Sapucai",
  "Sao Bernardo do Campo",
  "Sao Caetano do Sul",
  "Sao Carlos",
  "Sao Francisco",
  "Sao Joao da Boa Vista",
  "Sao Joao das Duas Pontes",
  "Sao Joao de Iracema",
  "Sao Joao do Pau d'Alho",
  "Sao Joaquim da Barra",
  "Sao Jose da Bela Vista",
  "Sao Jose do Barreiro",
  "Sao Jose do Rio Pardo",
  "Sao Jose do Rio Preto",
  "Sao Jose dos Campos",
  "Sao Lourenco da Serra",
  "Sao Luis do Paraitinga",
  "Sao Manuel",
  "Sao Miguel Arcanjo",
  "Sao Pedro do Turvo",
  "Sao Pedro",
  "Sao Roque",
  "Sao Sebastiao da Grama",
  "Sao Sebastiao",
  "Sao Simao",
  "Sao Vicente",
  "Sarapui",
  "Sarutaia",
  "Sebastianopolis do Sul",
  "Serra Azul",
  "Serra Negra",
  "Serrana",
  "Sertaozinho",
  "Sete Barras",
  "Severinia",
  "Silveiras",
  "Socorro",
  "Sorocaba",
  "Sud Mennucci",
  "Sumare",
  "Suzanapolis",
  "Suzano",
  "Tabapua",
  "Tabatinga",
  "Taboao da Serra",
  "Taciba",
  "Taguai",
  "Taiacu",
  "Taiuva",
  "Tambau",
  "Tanabi",
  "Tapirai",
  "Tapiratiba",
  "Taquaral",
  "Taquaritinga",
  "Taquarituba",
  "Taquarivai",
  "Tarabai",
  "Taruma",
  "Tatui",
  "Taubate",
  "Tejupa",
  "Teodoro Sampaio",
  "Terra Roxa",
  "Tiete",
  "Timburi",
  "Torre de Pedra",
  "Torrinha",
  "Trabiju",
  "Tremembe",
  "Tres Fronteiras",
  "Tuiuti",
  "Tupa",
  "Tupi Paulista",
  "Turiuba",
  "Turmalina",
  "Ubarana",
  "Ubatuba",
  "Ubirajara",
  "Uchoa",
  "Uniao Paulista",
  "Urania",
  "Uru",
  "Urupes",
  "Valentim Gentil",
  "Valinhos",
  "Valparaiso",
  "Vargem Grande Paulista",
  "Vargem Grande do Sul",
  "Vargem",
  "Varzea Paulista",
  "Vera Cruz",
  "Vinhedo",
  "Viradouro",
  "Vista Alegre do Alto",
  "Vitoria Brasil",
  "Votorantim",
  "Votuporanga",
  "Zacarias"
];

const cidadesMg = [
  "Belo Horizonte",
  "Abadia dos Dourados",
  "Abaete",
  "Abre Campo",
  "Acaiaca",
  "Acucena",
  "Agua Boa",
  "Agua Comprida",
  "Aguanil",
  "Aguas Formosas",
  "Aguas Vermelhas",
  "Aimores",
  "Aiuruoca",
  "Alagoa",
  "Albertina",
  "Alem Paraiba",
  "Alfenas",
  "Alfredo Vasconcelos",
  "Almenara",
  "Alpercata",
  "Alpinopolis",
  "Alterosa",
  "Alto Caparao",
  "Alto Jequitiba",
  "Alto Rio Doce",
  "Alvarenga",
  "Alvinopolis",
  "Alvorada de Minas",
  "Amparo do Serra",
  "Andradas",
  "Andrelandia",
  "Angelandia",
  "Antonio Carlos",
  "Antonio Dias",
  "Antonio Prado de Minas",
  "Aracai",
  "Aracitaba",
  "Aracuai",
  "Araguari",
  "Arantina",
  "Araponga",
  "Arapora",
  "Arapua",
  "Araujos",
  "Araxa",
  "Arceburgo",
  "Arcos",
  "Areado",
  "Argirita",
  "Aricanduva",
  "Arinos",
  "Astolfo Dutra",
  "Ataleia",
  "Augusto de Lima",
  "Baependi",
  "Baldim",
  "Bambui",
  "Bandeira do Sul",
  "Bandeira",
  "Barao de Cocais",
  "Barao de Monte Alto",
  "Barbacena",
  "Barra Longa",
  "Barroso",
  "Bela Vista de Minas",
  "Belmiro Braga",
  "Belo Oriente",
  "Belo Vale",
  "Berilo",
  "Berizal",
  "Bertopolis",
  "Betim",
  "Bias Fortes",
  "Bicas",
  "Biquinhas",
  "Boa Esperanca",
  "Bocaina de Minas",
  "Bocaiuva",
  "Bom Despacho",
  "Bom Jardim de Minas",
  "Bom Jesus da Penha",
  "Bom Jesus do Amparo",
  "Bom Jesus do Galho",
  "Bom Repouso",
  "Bom Sucesso",
  "Bonfim",
  "Bonfinopolis de Minas",
  "Bonito de Minas",
  "Borda da Mata",
  "Botelhos",
  "Botumirim",
  "Bras Pires",
  "Brasilandia de Minas",
  "Brasilia de Minas",
  "Brasopolis",
  "Braunas",
  "Brumadinho",
  "Bueno Brandao",
  "Buenopolis",
  "Bugre",
  "Buritis",
  "Buritizeiro",
  "Cabeceira Grande",
  "Cabo Verde",
  "Cachoeira Dourada",
  "Cachoeira da Prata",
  "Cachoeira de Minas",
  "Cachoeira de Pajeu",
  "Caetanopolis",
  "Caete",
  "Caiana",
  "Cajuri",
  "Caldas",
  "Camacho",
  "Camanducaia",
  "Cambui",
  "Cambuquira",
  "Campanario",
  "Campanha",
  "Campestre",
  "Campina Verde",
  "Campo Azul",
  "Campo Belo",
  "Campo Florido",
  "Campo do Meio",
  "Campos Altos",
  "Campos Gerais",
  "Cana Verde",
  "Canaa",
  "Canapolis",
  "Candeias",
  "Cantagalo",
  "Caparao",
  "Capela Nova",
  "Capelinha",
  "Capetinga",
  "Capim Branco",
  "Capinopolis",
  "Capitao Andrade",
  "Capitao Eneas",
  "Capitolio",
  "Caputira",
  "Carai",
  "Caranaiba",
  "Carandai",
  "Carangola",
  "Caratinga",
  "Carbonita",
  "Careacu",
  "Carlos Chagas",
  "Carmesia",
  "Carmo da Cachoeira",
  "Carmo da Mata",
  "Carmo de Minas",
  "Carmo do Cajuru",
  "Carmo do Paranaiba",
  "Carmo do Rio Claro",
  "Carmopolis de Minas",
  "Carneirinho",
  "Carrancas",
  "Carvalhopolis",
  "Carvalhos",
  "Casa Grande",
  "Cascalho Rico",
  "Cassia",
  "Cataguases",
  "Catas Altas da Noruega",
  "Catas Altas",
  "Catuji",
  "Catuti",
  "Caxambu",
  "Cedro do Abaete",
  "Central de Minas",
  "Centralina",
  "Chacara",
  "Chale",
  "Chapada Gaucha",
  "Chapada do Norte",
  "Chiador",
  "Cipotanea",
  "Claraval",
  "Claro dos Pocoes",
  "Claudio",
  "Coimbra",
  "Coluna",
  "Comendador Gomes",
  "Comercinho",
  "Conceicao da Aparecida",
  "Conceicao da Barra de Minas",
  "Conceicao das Alagoas",
  "Conceicao das Pedras",
  "Conceicao de Ipanema",
  "Conceicao do Mato Dentro",
  "Conceicao do Para",
  "Conceicao do Rio Verde",
  "Conceicao dos Ouros",
  "Conego Marinho",
  "Confins",
  "Congonhal",
  "Congonhas do Norte",
  "Congonhas",
  "Conquista",
  "Conselheiro Lafaiete",
  "Conselheiro Pena",
  "Consolacao",
  "Contagem",
  "Coqueiral",
  "Coracao de Jesus",
  "Cordisburgo",
  "Cordislandia",
  "Corinto",
  "Coroaci",
  "Coromandel",
  "Coronel Fabriciano",
  "Coronel Murta",
  "Coronel Pacheco",
  "Coronel Xavier Chaves",
  "Corrego Danta",
  "Corrego Fundo",
  "Corrego Novo",
  "Corrego do Bom Jesus",
  "Couto de Magalhaes de Minas",
  "Crisolita",
  "Cristais",
  "Cristalia",
  "Cristiano Otoni",
  "Cristina",
  "Crucilandia",
  "Cruzeiro da Fortaleza",
  "Cruzilia",
  "Cuparaque",
  "Curral de Dentro",
  "Curvelo",
  "Datas",
  "Delfim Moreira",
  "Delfinopolis",
  "Delta",
  "Descoberto",
  "Desterro de Entre Rios",
  "Desterro do Melo",
  "Diamantina",
  "Diogo de Vasconcelos",
  "Dionisio",
  "Divinesia",
  "Divino das Laranjeiras",
  "Divino",
  "Divinolandia de Minas",
  "Divinopolis",
  "Divisa Alegre",
  "Divisa Nova",
  "Divisopolis",
  "Dom Bosco",
  "Dom Cavati",
  "Dom Joaquim",
  "Dom Silverio",
  "Dom Vicoso",
  "Dona Euzebia",
  "Dores de Campos",
  "Dores de Guanhaes",
  "Dores do Indaia",
  "Dores do Turvo",
  "Doresopolis",
  "Douradoquara",
  "Durande",
  "Eloi Mendes",
  "Engenheiro Caldas",
  "Engenheiro Navarro",
  "Entre Folhas",
  "Entre Rios de Minas",
  "Ervalia",
  "Esmeraldas",
  "Espera Feliz",
  "Espinosa",
  "Espirito Santo do Dourado",
  "Estiva",
  "Estrela Dalva",
  "Estrela do Indaia",
  "Estrela do Sul",
  "Eugenopolis",
  "Ewbank da Camara",
  "Extrema",
  "Fama",
  "Faria Lemos",
  "Felicio dos Santos",
  "Felisburgo",
  "Felixlandia",
  "Fernandes Tourinho",
  "Ferros",
  "Fervedouro",
  "Florestal",
  "Formiga",
  "Formoso",
  "Fortaleza de Minas",
  "Fortuna de Minas",
  "Francisco Badaro",
  "Francisco Dumont",
  "Francisco Sa",
  "Franciscopolis",
  "Frei Gaspar",
  "Frei Inocencio",
  "Frei Lagonegro",
  "Fronteira dos Vales",
  "Fronteira",
  "Fruta de Leite",
  "Frutal",
  "Funilandia",
  "Galileia",
  "Gameleiras",
  "Glaucilandia",
  "Goiabeira",
  "Goiana",
  "Goncalves",
  "Gonzaga",
  "Gouvea",
  "Governador Valadares",
  "Grao Mogol",
  "Grupiara",
  "Guanhaes",
  "Guape",
  "Guaraciaba",
  "Guaraciama",
  "Guaranesia",
  "Guarani",
  "Guarara",
  "Guarda-Mor",
  "Guaxupe",
  "Guidoval",
  "Guimarania",
  "Guiricema",
  "Gurinhata",
  "Heliodora",
  "Iapu",
  "Ibertioga",
  "Ibia",
  "Ibiai",
  "Ibiracatu",
  "Ibiraci",
  "Ibirite",
  "Ibitiura de Minas",
  "Ibituruna",
  "Icarai de Minas",
  "Igarape",
  "Igaratinga",
  "Iguatama",
  "Ijaci",
  "Ilicinea",
  "Imbe de Minas",
  "Inconfidentes",
  "Indaiabira",
  "Indianopolis",
  "Ingai",
  "Inhapim",
  "Inhauma",
  "Inimutaba",
  "Ipaba",
  "Ipanema",
  "Ipatinga",
  "Ipiacu",
  "Ipuiuna",
  "Irai de Minas",
  "Itabira",
  "Itabirinha de Mantena",
  "Itabirito",
  "Itacambira",
  "Itacarambi",
  "Itaguara",
  "Itaipe",
  "Itajuba",
  "Itamarandiba",
  "Itamarati de Minas",
  "Itambacuri",
  "Itambe do Mato Dentro",
  "Itamogi",
  "Itamonte",
  "Itanhandu",
  "Itanhomi",
  "Itaobim",
  "Itapagipe",
  "Itapecerica",
  "Itapeva",
  "Itatiaiucu",
  "Itau de Minas",
  "Itauna",
  "Itaverava",
  "Itinga",
  "Itueta",
  "Ituiutaba",
  "Itumirim",
  "Iturama",
  "Itutinga",
  "Jaboticatubas",
  "Jacinto",
  "Jacui",
  "Jacutinga",
  "Jaguaracu",
  "Jaiba",
  "Jampruca",
  "Janauba",
  "Januaria",
  "Japaraiba",
  "Japonvar",
  "Jeceaba",
  "Jenipapo de Minas",
  "Jequeri",
  "Jequitai",
  "Jequitiba",
  "Jequitinhonha",
  "Jesuania",
  "Joaima",
  "Joanesia",
  "Joao Monlevade",
  "Joao Pinheiro",
  "Joaquim Felicio",
  "Jordania",
  "Jose Goncalves de Minas",
  "Jose Raydan",
  "Josenopolis",
  "Juatuba",
  "Juiz de Fora",
  "Juramento",
  "Juruaia",
  "Juvenilia",
  "Ladainha",
  "Lagamar",
  "Lagoa Dourada",
  "Lagoa Formosa",
  "Lagoa Grande",
  "Lagoa Santa",
  "Lagoa da Prata",
  "Lagoa dos Patos",
  "Lagoas",
  "Lajinha",
  "Lambari",
  "Lamim",
  "Laranjal",
  "Lassance",
  "Lavras",
  "Leandro Ferreira",
  "Leme do Prado",
  "Leopoldina",
  "Liberdade",
  "Lima Duarte",
  "Limeira do Oeste",
  "Lontra",
  "Luisburgo",
  "Luislandia",
  "Luminarias",
  "Luz",
  "Machacalis",
  "Machado",
  "Madre de Deus de Minas",
  "Malacacheta",
  "Mamonas",
  "Manga",
  "Manhuacu",
  "Manhumirim",
  "Mantena",
  "Mar de Espanha",
  "Maravilhas",
  "Maria da Fe",
  "Mariana",
  "Marilac",
  "Mario Campos",
  "Maripa de Minas",
  "Marlieria",
  "Marmelopolis",
  "Martinho Campos",
  "Martins Soares",
  "Mata Verde",
  "Materlandia",
  "Mateus Leme",
  "Mathias Lobato",
  "Matias Barbosa",
  "Matias Cardoso",
  "Matipo",
  "Mato Verde",
  "Matozinhos",
  "Matutina",
  "Medeiros",
  "Medina",
  "Mendes Pimentel",
  "Merces",
  "Mesquita",
  "Minas Novas",
  "Minduri",
  "Mirabela",
  "Miradouro",
  "Mirai",
  "Miravania",
  "Moeda",
  "Moema",
  "Monjolos",
  "Monsenhor Paulo",
  "Montalvania",
  "Monte Alegre de Minas",
  "Monte Azul",
  "Monte Belo",
  "Monte Carmelo",
  "Monte Formoso",
  "Monte Santo de Minas",
  "Monte Siao",
  "Montes Claros",
  "Montezuma",
  "Morada Nova de Minas",
  "Morro da Garca",
  "Morro do Pilar",
  "Munhoz",
  "Muriae",
  "Mutum",
  "Muzambinho",
  "Nacip Raydan",
  "Nanuque",
  "Naque",
  "Natalandia",
  "Natercia",
  "Nazareno",
  "Nepomuceno",
  "Ninheira",
  "Nova Belem",
  "Nova Era",
  "Nova Lima",
  "Nova Modica",
  "Nova Ponte",
  "Nova Porteirinha",
  "Nova Resende",
  "Nova Serrana",
  "Nova Uniao",
  "Novo Cruzeiro",
  "Novo Oriente de Minas",
  "Novorizonte",
  "Olaria",
  "Olhos-d'Agua",
  "Olimpio Noronha",
  "Oliveira Fortes",
  "Oliveira",
  "Onca de Pitangui",
  "Oratorios",
  "Orizania",
  "Ouro Branco",
  "Ouro Fino",
  "Ouro Preto",
  "Ouro Verde de Minas",
  "Padre Carvalho",
  "Padre Paraiso",
  "Pai Pedro",
  "Paineiras",
  "Pains",
  "Paiva",
  "Palma",
  "Palmopolis",
  "Papagaios",
  "Para de Minas",
  "Paracatu",
  "Paraguacu",
  "Paraisopolis",
  "Paraopeba",
  "Passa Quatro",
  "Passa Tempo",
  "Passa Vinte",
  "Passabem",
  "Passos",
  "Patis",
  "Patos de Minas",
  "Patrocinio do Muriae",
  "Patrocinio",
  "Paula Candido",
  "Paulistas",
  "Pavao",
  "Pecanha",
  "Pedra Azul",
  "Pedra Bonita",
  "Pedra Dourada",
  "Pedra do Anta",
  "Pedra do Indaia",
  "Pedralva",
  "Pedras de Maria da Cruz",
  "Pedrinopolis",
  "Pedro Leopoldo",
  "Pedro Teixeira",
  "Pequeri",
  "Pequi",
  "Perdigao",
  "Perdizes",
  "Perdoes",
  "Periquito",
  "Pescador",
  "Piau",
  "Piedade de Caratinga",
  "Piedade de Ponte Nova",
  "Piedade do Rio Grande",
  "Piedade dos Gerais",
  "Pimenta",
  "Pingo d'Agua",
  "Pintopolis",
  "Piracema",
  "Pirajuba",
  "Piranga",
  "Pirangucu",
  "Piranguinho",
  "Pirapetinga",
  "Pirapora",
  "Pirauba",
  "Pitangui",
  "Piui",
  "Planura",
  "Poco Fundo",
  "Pocos de Caldas",
  "Pocrane",
  "Pompeu",
  "Ponte Nova",
  "Ponto Chique",
  "Ponto dos Volantes",
  "Porteirinha",
  "Porto Firme",
  "Pote",
  "Pouso Alegre",
  "Pouso Alto",
  "Prados",
  "Prata",
  "Pratapolis",
  "Pratinha",
  "Presidente Bernardes",
  "Presidente Juscelino",
  "Presidente Kubitschek",
  "Presidente Olegario",
  "Prudente de Morais",
  "Quartel Geral",
  "Queluzita",
  "Raposos",
  "Raul Soares",
  "Recreio",
  "Reduto",
  "Resende Costa",
  "Resplendor",
  "Ressaquinha",
  "Riachinho",
  "Riacho dos Machados",
  "Ribeirao Vermelho",
  "Ribeirao das Neves",
  "Rio Acima",
  "Rio Casca",
  "Rio Doce",
  "Rio Espera",
  "Rio Manso",
  "Rio Novo",
  "Rio Paranaiba",
  "Rio Pardo de Minas",
  "Rio Piracicaba",
  "Rio Pomba",
  "Rio Preto",
  "Rio Vermelho",
  "Rio do Prado",
  "Ritapolis",
  "Rochedo de Minas",
  "Rodeiro",
  "Romaria",
  "Rosario da Limeira",
  "Rubelita",
  "Rubim",
  "Sabara",
  "Sabinopolis",
  "Sacramento",
  "Salinas",
  "Salto da Divisa",
  "Santa Barbara do Leste",
  "Santa Barbara do Monte Verde",
  "Santa Barbara do Tugurio",
  "Santa Barbara",
  "Santa Cruz de Minas",
  "Santa Cruz de Salinas",
  "Santa Cruz do Escalvado",
  "Santa Efigenia de Minas",
  "Santa Fe de Minas",
  "Santa Helena de Minas",
  "Santa Juliana",
  "Santa Luzia",
  "Santa Margarida",
  "Santa Maria de Itabira",
  "Santa Maria do Salto",
  "Santa Maria do Suacui",
  "Santa Rita de Caldas",
  "Santa Rita de Ibitipoca",
  "Santa Rita de Jacutinga",
  "Santa Rita de Minas",
  "Santa Rita do Itueto",
  "Santa Rita do Sapucai",
  "Santa Rosa da Serra",
  "Santa Vitoria",
  "Santana da Vargem",
  "Santana de Cataguases",
  "Santana de Pirapama",
  "Santana do Deserto",
  "Santana do Garambeu",
  "Santana do Jacare",
  "Santana do Manhuacu",
  "Santana do Paraiso",
  "Santana do Riacho",
  "Santana dos Montes",
  "Santo Antonio do Amparo",
  "Santo Antonio do Aventureiro",
  "Santo Antonio do Grama",
  "Santo Antonio do Itambe",
  "Santo Antonio do Jacinto",
  "Santo Antonio do Monte",
  "Santo Antonio do Retiro",
  "Santo Antonio do Rio Abaixo",
  "Santo Hipolito",
  "Santos Dumont",
  "Sao Bento Abade",
  "Sao Bras do Suacui",
  "Sao Domingos das Dores",
  "Sao Domingos do Prata",
  "Sao Felix de Minas",
  "Sao Francisco de Paula",
  "Sao Francisco de Sales",
  "Sao Francisco do Gloria",
  "Sao Francisco",
  "Sao Geraldo da Piedade",
  "Sao Geraldo do Baixio",
  "Sao Geraldo",
  "Sao Goncalo do Abaete",
  "Sao Goncalo do Para",
  "Sao Goncalo do Rio Abaixo",
  "Sao Goncalo do Rio Preto",
  "Sao Goncalo do Sapucai",
  "Sao Gotardo",
  "Sao Joao Batista do Gloria",
  "Sao Joao Evangelista",
  "Sao Joao Nepomuceno",
  "Sao Joao da Lagoa",
  "Sao Joao da Mata",
  "Sao Joao da Ponte",
  "Sao Joao das Missoes",
  "Sao Joao del Rei",
  "Sao Joao do Manhuacu",
  "Sao Joao do Manteninha",
  "Sao Joao do Oriente",
  "Sao Joao do Pacui",
  "Sao Joao do Paraiso",
  "Sao Joaquim de Bicas",
  "Sao Jose da Barra",
  "Sao Jose da Lapa",
  "Sao Jose da Safira",
  "Sao Jose da Varginha",
  "Sao Jose do Alegre",
  "Sao Jose do Divino",
  "Sao Jose do Goiabal",
  "Sao Jose do Jacuri",
  "Sao Jose do Mantimento",
  "Sao Lourenco",
  "Sao Miguel do Anta",
  "Sao Pedro da Uniao",
  "Sao Pedro do Suacui",
  "Sao Pedro dos Ferros",
  "Sao Romao",
  "Sao Roque de Minas",
  "Sao Sebastiao da Bela Vista",
  "Sao Sebastiao da Vargem Alegre",
  "Sao Sebastiao do Anta",
  "Sao Sebastiao do Maranhao",
  "Sao Sebastiao do Oeste",
  "Sao Sebastiao do Paraiso",
  "Sao Sebastiao do Rio Preto",
  "Sao Sebastiao do Rio Verde",
  "Sao Thome das Letras",
  "Sao Tiago",
  "Sao Tomas de Aquino",
  "Sao Vicente de Minas",
  "Sapucai-Mirim",
  "Sardoa",
  "Sarzedo",
  "Sem-Peixe",
  "Senador Amaral",
  "Senador Cortes",
  "Senador Firmino",
  "Senador Jose Bento",
  "Senador Modestino Goncalves",
  "Senhora de Oliveira",
  "Senhora do Porto",
  "Senhora dos Remedios",
  "Sericita",
  "Seritinga",
  "Serra Azul de Minas",
  "Serra da Saudade",
  "Serra do Salitre",
  "Serra dos Aimores",
  "Serrania",
  "Serranopolis de Minas",
  "Serranos",
  "Serro",
  "Sete Lagoas",
  "Setubinha",
  "Silveirania",
  "Silvianopolis",
  "Simao Pereira",
  "Simonesia",
  "Sobralia",
  "Soledade de Minas",
  "Tabuleiro",
  "Taiobeiras",
  "Taparuba",
  "Tapira",
  "Tapirai",
  "Taquaracu de Minas",
  "Tarumirim",
  "Teixeiras",
  "Teofilo Otoni",
  "Timoteo",
  "Tiradentes",
  "Tiros",
  "Tocantins",
  "Tocos do Moji",
  "Toledo",
  "Tombos",
  "Tres Coracoes",
  "Tres Marias",
  "Tres Pontas",
  "Tumiritinga",
  "Tupaciguara",
  "Turmalina",
  "Turvolandia",
  "Uba",
  "Ubai",
  "Ubaporanga",
  "Uberaba",
  "Uberlandia",
  "Umburatiba",
  "Unai",
  "Uniao de Minas",
  "Uruana de Minas",
  "Urucania",
  "Urucuia",
  "Vargem Alegre",
  "Vargem Bonita",
  "Vargem Grande do Rio Pardo",
  "Varginha",
  "Varjao de MInas",
  "Varzea da Palma",
  "Varzelandia",
  "Vazante",
  "Verdelandia",
  "Veredinha",
  "Verissimo",
  "Vermelho Novo",
  "Vespasiano",
  "Vicosa",
  "Vieiras",
  "Virgem da Lapa",
  "Virginia",
  "Virginopolis",
  "Virgolandia",
  "Visconde do Rio Branco",
  "Volta Grande",
  "Wenceslau Braz"
];
